### ISSUE TITLE
[Question] wonder about the switch from Tailwind CSS to Styled Components

### ISSUE THREAD

**Issue by orthinkzai** [bhouston/template-typescript-monorepo#19]
I'm a big fan of your template and appreciate the work you've put into it. 
I noticed the switch from Tailwind CSS to Styled Components and was curious about the reasoning behind it. I liked the simplicity of Tailwind and wondered if it's possible to support both in the template for added flexibility. Your insights on this decision would be valuable. 

Thanks for your time and your fantastic template!

**Comment by bhouston** [comment]
You can use the template version where it has tailwind css in it?  Or you can look at the PR where I remove it.  It is pretty straight forward.

The issue we ran into was that others are using our libraries and they may not be using tailwind, and thus using that library imposed it on them.  This was causing issues.  Now they can just pull in our React components and it instantly works without any additional build steps or configuration -- I guess that is the main benefit of styled-components, less complexity.

**Comment by orthinkzai** [comment]
yes I ll use the tailwind version thank you!
